const CURRENTUSER = 'CURRENTUSER'
const STOCKS = 'STOCKS'
const WATCHLIST = 'WATCHLIST'
const FILTER = 'FILTER'
const SEARCHRESULT = 'SEARCHRESULT'
const CURRENTSTOCK = 'CURRENTSTOCK'
const SHOWSTOCK = 'SHOWSTOCK'
const NEWS = 'NEWS'

export {
  CURRENTUSER,
  STOCKS,
  WATCHLIST,
  FILTER,
  SEARCHRESULT,
  CURRENTSTOCK,
  SHOWSTOCK,
  NEWS
}